auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: VRCEUS 
url: https://vrceus.github.io/
feed: /atom.xml
author_info: <a href="https://vrceus.github.io/">Vrceus</a>
